/*
 * File: app/view/pnAddListMoneyWindows.js
 *
 * This file was generated by Sencha Architect version 2.2.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.pnAddListMoneyWindows', {
    extend: 'Ext.window.Window',
    alias: 'widget.pnAddListMoneyWindows',

    height: 416,
    width: 604,
    layout: {
        type: 'border'
    },
    title: 'เพิ่มข้อมูลรับเงิน',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    region: 'center',
                    id: 'pnAddListMoney',
                    items: [
                        {
                            xtype: 'fieldset',
                            margin: '10 10 10 10',
                            padding: 10,
                            title: '',
                            items: [
                                {
                                    xtype: 'textfield',
                                    id: 'id',
                                    fieldLabel: 'รหัส',
                                    msgTarget: 'side',
                                    name: 'id',
                                    allowBlank: false,
                                    vtype: 'alphanum'
                                },
                                {
                                    xtype: 'datefield',
                                    id: 'date',
                                    fieldLabel: 'วันที่โอน',
                                    msgTarget: 'side',
                                    name: 'date',
                                    editable: false
                                },
                                {
                                    xtype: 'textfield',
                                    fieldLabel: 'เวลา',
                                    msgTarget: 'side',
                                    name: 'time'
                                },
                                {
                                    xtype: 'textfield',
                                    id: 'depNo',
                                    fieldLabel: 'หมายเลขรายการ',
                                    msgTarget: 'side',
                                    name: 'depNo',
                                    vtype: 'alphanum'
                                },
                                {
                                    xtype: 'textfield',
                                    id: 'withDrawal',
                                    fieldLabel: 'จำนวนที่ถอน',
                                    msgTarget: 'side',
                                    name: 'withDrawal',
                                    allowBlank: false,
                                    vtype: 'alphanum'
                                },
                                {
                                    xtype: 'textfield',
                                    id: 'deposit',
                                    fieldLabel: 'จำนวนที่ฝาก',
                                    msgTarget: 'side',
                                    name: 'deposit',
                                    allowBlank: false,
                                    vtype: 'alphanum'
                                },
                                {
                                    xtype: 'textfield',
                                    id: 'machNo',
                                    fieldLabel: 'machNo',
                                    msgTarget: 'side',
                                    name: 'machNo',
                                    vtype: 'alphanum'
                                },
                                {
                                    xtype: 'textfield',
                                    id: 'memberId',
                                    fieldLabel: 'memberId',
                                    msgTarget: 'side',
                                    name: 'memberId',
                                    vtype: 'alphanum'
                                },
                                {
                                    xtype: 'textfield',
                                    id: 'transactiionNo',
                                    fieldLabel: 'transactionNo',
                                    msgTarget: 'side',
                                    name: 'transactiionNo',
                                    vtype: 'alphanum'
                                },
                                {
                                    xtype: 'textfield',
                                    id: 'name',
                                    fieldLabel: 'ชื่อสมาชิก',
                                    msgTarget: 'side',
                                    name: 'name',
                                    vtype: 'alpha'
                                }
                            ]
                        },
                        {
                            xtype: 'button',
                            id: 'btnSave',
                            itemId: 'btnSave',
                            margin: '0 0 0 10',
                            width: 100,
                            text: 'บันทึก'
                        },
                        {
                            xtype: 'button',
                            id: 'btnClear',
                            margin: '0 0 0 10',
                            width: 100,
                            text: 'ล้างข้อมูล'
                        },
                        {
                            xtype: 'button',
                            id: 'btnEdit',
                            margin: '0 0 0 10',
                            width: 100,
                            text: 'แก้ไขข้อมูล'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});