/*
 * File: app/controller/MyController.js
 *
 * This file was generated by Sencha Architect version 2.2.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.MyController', {
    extend: 'Ext.app.Controller',

    refs: [
        {
            ref: 'pnAddListMoneyWindows',
            selector: 'pnAddListMoneyWindows'
        },
        {
            ref: 'wdForm',
            selector: 'wnDelete'
        }
    ],

    clickAddmoney: function(button, e, eOpts) {
        //console.log('ooooooooooo');
        this.loadAdd();
    },

    clickAddButton: function(button, e, eOpts) {
        console.log(Ext.getCmp('pnAddListMoney').getForm().isValid());
        if(Ext.getCmp('pnAddListMoney').getForm().isValid())
        {

            Ext.getStore('cultData').add(Ext.getCmp('pnAddListMoney').getForm().getValues());
            Ext.getCmp('pnAddListMoney').getForm().reset;
            this.getPnAddListMoneyWindows().destroy();

        }

    },

    clickSubmitEdit: function(button, e, eOpts) {

        rec.set(Ext.getCmp('pnAddListMoney').getForm().getValues());
        this.getPnAddListMoneyWindows().destroy();


    },

    clickNo: function(button, e, eOpts) {
        this.getWdForm().destroy();
    },

    clickClear: function(button, e, eOpts) {
        Ext.getCmp('pnAddListMoney').getForm().reset();
    },

    clickEdit: function(column,action,view, rowIndex, colIndex, item, e,record,row) {
        //console.log('jjjjjjj');


        rec = record;
        var wnDel = Ext.create('MyApp.view.wnDelete');
        indexRow = rowIndex;


        var getloadEdit = Ext.getStore('cultData').data.items[rowIndex];

        var store =  Ext.getStore('cultData');

        if (action == 'dle'){
            wnDel.show();
            //store.removeAt(rowIndex);
        }
        else{

            this.loadEdit(getloadEdit,rowIndex);


        }






    },

    clickYes: function(button, e, eOpts) {
        //console.log(button,e,eOpts);
        this.rowDelete(indexRow);

        this.getWdForm().destroy();
    },

    loadAdd: function() {

        var pnWindow = Ext.getCmp('pnAddListMoneyWindows');

        if(!pnWindow){
            pnWindow = Ext.create('MyApp.view.pnAddListMoneyWindows');
            Ext.getCmp('btnEdit').hidden = true;

        }

        pnWindow.show();


    },

    loadEdit: function(loadInfo, rowIndex) {

        var pnWindow = Ext.create('MyApp.view.pnAddListMoneyWindows',{
            title:"แก้ไขข้อมูลรับเงิน"

        });

        Ext.getCmp('btnSave').hidden = true;
        pnWindow.show();


        /*
        for (prop in loadInfo.data){
        console.log(prop);
        //console.log(loadInfo.data[prop]);
        //console.log(Ext.getCmp(prop));
        //  Ext.getCmp[prop].setValue(loadInfo.data[prop]);

        Ext.getCmp(prop).setValue(loadInfo.data[prop]);
    }
    */

    var rstore=Ext.getStore('cultData').getAt(rowIndex);
    Ext.getCmp('pnAddListMoney').getForm().loadRecord(rstore);

    //this.getPnAddListMoneyWindows().destroy();
    },

    rowDelete: function(rowinfo) {
        var store = Ext.getStore('cultData');

        store.removeAt(rowinfo);
    },

    init: function(application) {
        this.control({
            "#btnAdd": {
                click: this.clickAddmoney
            },
            "#btnSave": {
                click: this.clickAddButton
            },
            "#btnEdit": {
                click: this.clickSubmitEdit
            },
            "#btnNo": {
                click: this.clickNo
            },
            "#btnClear": {
                click: this.clickClear
            },
            "mygridpanel actioncolumn": {
                itemclick: this.clickEdit
            },
            "#btnYes": {
                click: this.clickYes
            }
        });
    }

});
